package com.example.psklab1.mybatis.model;

public class Optionalcourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OPTIONALCOURSE.ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OPTIONALCOURSE.NAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OPTIONALCOURSE.ID
     *
     * @return the value of PUBLIC.OPTIONALCOURSE.ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OPTIONALCOURSE.ID
     *
     * @param id the value for PUBLIC.OPTIONALCOURSE.ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OPTIONALCOURSE.NAME
     *
     * @return the value of PUBLIC.OPTIONALCOURSE.NAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OPTIONALCOURSE.NAME
     *
     * @param name the value for PUBLIC.OPTIONALCOURSE.NAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}