package com.example.psklab1.mybatis.model;

public class StudentGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTGROUP.ID
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTGROUP.COURSE
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    private Integer course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTGROUP.SPECIALTY
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    private String specialty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTGROUP.ID
     *
     * @return the value of PUBLIC.STUDENTGROUP.ID
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTGROUP.ID
     *
     * @param id the value for PUBLIC.STUDENTGROUP.ID
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTGROUP.COURSE
     *
     * @return the value of PUBLIC.STUDENTGROUP.COURSE
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    public Integer getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTGROUP.COURSE
     *
     * @param course the value for PUBLIC.STUDENTGROUP.COURSE
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    public void setCourse(Integer course) {
        this.course = course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTGROUP.SPECIALTY
     *
     * @return the value of PUBLIC.STUDENTGROUP.SPECIALTY
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTGROUP.SPECIALTY
     *
     * @param specialty the value for PUBLIC.STUDENTGROUP.SPECIALTY
     *
     * @mbg.generated Sat Apr 06 19:03:35 EEST 2024
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }
}