package com.example.psklab1.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    private Long studentgroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @return the value of PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LASTNAME
     *
     * @param lastname the value for PUBLIC.STUDENT.LASTNAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public Long getStudentgroupId() {
        return studentgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @param studentgroupId the value for PUBLIC.STUDENT.STUDENTGROUP_ID
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    public void setStudentgroupId(Long studentgroupId) {
        this.studentgroupId = studentgroupId;
    }
}