package com.example.psklab1.mybatis.model;

public class Studentas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTAS.ID
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTAS.PAVARDE
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    private String pavarde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTAS.VARDAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENTAS.GRUPE_ID
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    private Long grupeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTAS.ID
     *
     * @return the value of PUBLIC.STUDENTAS.ID
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTAS.ID
     *
     * @param id the value for PUBLIC.STUDENTAS.ID
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTAS.PAVARDE
     *
     * @return the value of PUBLIC.STUDENTAS.PAVARDE
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public String getPavarde() {
        return pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTAS.PAVARDE
     *
     * @param pavarde the value for PUBLIC.STUDENTAS.PAVARDE
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public void setPavarde(String pavarde) {
        this.pavarde = pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTAS.VARDAS
     *
     * @return the value of PUBLIC.STUDENTAS.VARDAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTAS.VARDAS
     *
     * @param vardas the value for PUBLIC.STUDENTAS.VARDAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENTAS.GRUPE_ID
     *
     * @return the value of PUBLIC.STUDENTAS.GRUPE_ID
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public Long getGrupeId() {
        return grupeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENTAS.GRUPE_ID
     *
     * @param grupeId the value for PUBLIC.STUDENTAS.GRUPE_ID
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    public void setGrupeId(Long grupeId) {
        this.grupeId = grupeId;
    }
}