package com.example.psklab1.mybatis.dao;

import com.example.psklab1.mybatis.model.OptionalCourse;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface OptionalCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSE
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSE
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    int insert(OptionalCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSE
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    OptionalCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSE
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    List<OptionalCourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSE
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    int updateByPrimaryKey(OptionalCourse record);
}