package com.example.psklab1.mybatis.dao;

import com.example.psklab1.mybatis.model.Pasirenkamaskursas;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PasirenkamaskursasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    int insert(Pasirenkamaskursas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    Pasirenkamaskursas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    List<Pasirenkamaskursas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASKURSAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    int updateByPrimaryKey(Pasirenkamaskursas record);
}