package com.example.psklab1.mybatis.dao;

import com.example.psklab1.mybatis.model.Studentas;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudentasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    int insert(Studentas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    Studentas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    List<Studentas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Fri Mar 15 17:50:13 EET 2024
     */
    int updateByPrimaryKey(Studentas record);
}