package com.example.psklab1.mybatis.dao;

import com.example.psklab1.mybatis.model.Studentgroup;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudentgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    int insert(Studentgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    Studentgroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    List<Studentgroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTGROUP
     *
     * @mbg.generated Sat Mar 16 20:39:50 EET 2024
     */
    int updateByPrimaryKey(Studentgroup record);
}